baseurl = "/"
languageCode = "en-us"
pagination.pagerSize = 5
# theme = "terminal"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true

[params]

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "" 

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # auto cover image from /static
  autoCover = true

  # post last updated options
  showLastUpdated = false
  enableGitInfo = false

  # ðŸ‘‰ CUSTOM CSS + JS (Required for mobile menu fix)
  customCSS = ["css/menu.css"]
  customJS = ["js/menu.js"]

[params.twitter]
  creator = ""
  site = ""

[languages]

  [languages.en]
    languageName = "English"
    title = "Terminal"

    [languages.en.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = "KitKat"
      keywords = ""
      copyright = ""

      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      missingBackButtonURL = "/"

      [languages.en.params.logo]
        logoText = "Terminal"

      [languages.en.menu]

        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "showcase"
          name = "Blog"
          url = "/blogs/showcase"
          weight = 3

  [languages.pl]
    languageName = "Polski"
    title = "Terminal"

    [languages.pl.params]
      subtitle = "Prosty theme w stylu retro dla Hugo"
      owner = ""
      keywords = ""

      readMore = "Czytaj dalej"
      readOtherPosts = "Zobacz wiÄ™cej postÃ³w"
      newerPosts = "Nowsze posty"
      olderPosts = "Starsze posty"
      missingContentMessage = "Nie odnaleziono strony..."
      missingBackButtonLabel = "WrÃ³Ä‡ do strony gÅ‚Ã³wnej"

    [languages.pl.params.logo]
      logoText = "Terminal"

    [languages.pl.menu]

      [[languages.pl.menu.main]]
        identifier = "about"
        name = "O motywie"
        url = "/pl/about"

      [[languages.pl.menu.main]]
        identifier = "showcase"
        name = "Prezentacja"
        url = "/blogs/showcase"

# ðŸ‘‰ Mount custom CSS & JS folders (Required for Hugo to load assets)
[[module.mounts]]
  source = "assets/css"
  target = "assets/css"

[[module.mounts]]
  source = "assets/js"
  target = "assets/js"

# Import the Terminal theme
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'
